logging:
    level:
        org:
            hibernate: ERROR

server:
    port: 8080

spring:
    application:
        name: customer
    datasource:
        password: 123456
        url: jdbc:mysql://localhost:3306/customer?createDatabaseIfNotExist=true&useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
        show-sql: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true